### ISSUE TITLE
Should obtain SA token from token secret

### ISSUE THREAD

**Issue by erikgb** [maxgio92/proxy-kubeconfig-generator#3]
This tool does not seem to work on Openshift, as it attempts to obtain the SA token from the Openshift registry image pull secret. This is an automated secret created for all SA in Openshift clusters. I think the algorithm to find the correct secret (containing a token) must be improved.

````
$ proxy-kubeconfig-generator --kubeconfig-secret-key kubeconfig --namespace erikbo --server 'https://capsule-proxy.capsule-system.svc:9001' --server-tls-secret-namespace capsule-system --server-tls-secret-name capsule-proxy --serviceaccount gitops-reconciler
panic: secret gitops-reconciler-dockercfg-qv5nr does not contain a token

goroutine 1 [running]:
main.main()
        /home/erikbo/go/pkg/mod/github.com/maxgio92/proxy-kubeconfig-generator@v0.1.0/main.go:68 +0x434
````

Ref. https://capsule.clastix.io/docs/guides/flux2-capsule/#the-recipe

**Comment by maxgio92** [comment]
Hi @erikgb, thank you for reporting this.

TL;DR this tool doesn't support as of now Kubernetes >= 1.24.

From Kubernetes 1.24 Service Account token are no longer automatically generated, when a Service Account is created ([docs](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts))
This tool instead assumes a Service Account token exists as a `Secret` object, related to the `ServiceAccount` object. 

I'm sorry this is not stated clearly in the readme.

Anyway, we can think of a better way to manage this situation, if possible, without introducing breaking changes.

**Comment by maxgio92** [comment]
In any case, this is a non-well managed error, as it would be better to not panic, thank you.

**Comment by erikgb** [comment]
> From Kubernetes 1.24 Service Account token are no longer automatically generated, when a Service Account is created ([docs](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts)) This tool instead assumes a Service Account token exists as a `Secret` object, related to the `ServiceAccount` object.

Even if Kubernetes stopped generating SA token secrets, OpenShift still do. We are on OpenShift 4.12 (Kubernetes 1.25). The secret with the token is there, but there is another secret that seems to confuse the tool. I think it should be fixed by looking for the correct secret containing the token. And if no such secret exists, it should error out - of course.

**Comment by erikgb** [comment]
If it looks for secrets of the correct type (`kubernetes.io/service-account-token`), this should be fixed:

````yaml
kind: Secret
apiVersion: v1
metadata:
  name: gitops-reconciler-token-hsglk
  namespace: erikbo
  annotations:
    kubernetes.io/created-by: openshift.io/create-dockercfg-secrets
    kubernetes.io/service-account.name: gitops-reconciler
    kubernetes.io/service-account.uid: 8d649e38-54dd-413c-811a-8530b950f4a1
data:
  token: ...
type: kubernetes.io/service-account-token
````
